name: Build and Push to Develop-Dist Branch

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Push
        run: |
          git config set advice.addIgnoredFile false && mkdir -p dist && cp package.json dist/ && git add dist/ package.json -f && git commit -m "Auto Build Dist: ({sha}) {msg}" && git push origin develop-dist -f
